// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    public partial class DeferredProducts
    {
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public int Id { get; set; }

        public virtual Products Product { get; set; }
        public virtual Users User { get; set; }
    }
}