// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    public partial class Files
    {
        public Files()
        {
            TableFiles = new HashSet<TableFiles>();
        }

        public int Id { get; set; }
        public string FileTitle { get; set; } = null!;
        public string FilePath { get; set; } = null!;

        public virtual ICollection<TableFiles> TableFiles { get; set; }
    }
}