// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    public partial class Orders
    {
        public Orders()
        {
            OrderHistory = new HashSet<OrderHistory>();
        }

        public int Id { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public int? ProductCount { get; set; }
        public int PickUpPointId { get; set; }
        public double? Price { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? EstimatedDeliveryAt { get; set; }

        public virtual Storages PickUpPoint { get; set; }
        public virtual Products Product { get; set; }
        public virtual Users User { get; set; }
        public virtual Reviews Reviews { get; set; }
        public virtual ICollection<OrderHistory> OrderHistory { get; set; } 
    }
}