// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    public partial class OrderStatuses
    {
        public OrderStatuses()
        {
            OrderHistory = new HashSet<OrderHistory>();
        }

        public int Id { get; set; }
        public string Description { get; set; } = null!;

        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
    }
}