// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    public partial class OrderHistory
    {
        public OrderHistory()
        {
            Worker = new HashSet<Workers>();
        }

        public int OrderId { get; set; }
        public DateTime StatusChangedAt { get; set; }
        public int? StatusId { get; set; }
        public int? CurrentStorageId { get; set; }
        public bool? IsLastStatus { get; set; }

        public virtual Storages CurrentStorage { get; set; }
        public virtual Orders Order { get; set; }
        public virtual OrderStatuses Status { get; set; }

        public virtual ICollection<Workers> Worker { get; set; }
    }
}