// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    public partial class Posts
    {
        public Posts()
        {
            SectionRights = new HashSet<SectionRights>();
            Workers = new HashSet<Workers>();
        }

        public int Id { get; set; }
        public string Title { get; set; }

        public virtual ICollection<SectionRights> SectionRights { get; set; }
        public virtual ICollection<Workers> Workers { get; set; }
    }
}