// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace WpfApp1.Models
{
    public partial class Products : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        public void OnPropertyChanged([CallerMemberName] string prop = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(prop));
        }

        public Products()
        {
            DeferredProducts = new HashSet<DeferredProducts>();
            Orders = new HashSet<Orders>();
            PriceHistory = new HashSet<PriceHistory>();
            ProductsOnStorages = new HashSet<ProductsOnStorages>();
            ProductsParameters = new HashSet<ProductsParameters>();
            ReceiptOfProductsToStorages = new HashSet<ReceiptOfProductsToStorages>();
            Images = new HashSet<ProductImage>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public double Price { get; set; }
        public int SupplierId { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public double SupplierPercent { get; set; }

        public virtual Categories Category { get; set; }
        public virtual Suppliers Supplier { get; set; }
        public virtual ICollection<DeferredProducts> DeferredProducts { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<PriceHistory> PriceHistory { get; set; }
        public virtual ICollection<ProductsOnStorages> ProductsOnStorages { get; set; }
        public virtual ICollection<ProductsParameters> ProductsParameters { get; set; }
        public virtual ICollection<ReceiptOfProductsToStorages> ReceiptOfProductsToStorages { get; set; }
        public virtual ICollection<PriceHistory> PriceHistories { get; set; }

        private ICollection<ProductImage> _images; 
        public virtual ICollection<ProductImage> Images {
            get => _images;
            set
            {
                _images = value;
                OnPropertyChanged();
            }
        }
    }
}