// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    public partial class ReceiptOfProductsToStorages
    {
        public int ProductId { get; set; }
        public int StorageId { get; set; }
        public DateTime ReceivedAt { get; set; }
        public int Amount { get; set; }

        public virtual Products Product { get; set; }
        public virtual Storages Storage { get; set; }
    }
}