// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    /// <summary>
    /// Модель, описывающая виды прав к разделам.
    /// </summary>
    public partial class Rights
    {
        public Rights()
        {
            SectionRights = new HashSet<SectionRights>();
        }

        public int Id { get; set; }
        public string Title { get; set; }

        public virtual ICollection<SectionRights> SectionRights { get; set; }
    }
}