// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    public partial class Sections
    {
        public Sections()
        {
            SectionRights = new HashSet<SectionRights>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public int? ParentId { get; set; }
        public string SectionKey { get; set; }

        public virtual ICollection<SectionRights> SectionRights { get; set; }
    }
}