// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    /// <summary>
    /// Модель, описывающая права на действия с разделами.
    /// </summary>
    public partial class SectionRights
    {
        public int Id { get; set; }
        public int? SectionId { get; set; }
        public int? RightId { get; set; }
        public int? PostId { get; set; }

        public virtual Posts Post { get; set; }
        public virtual Rights Right { get; set; }
        public virtual Sections Section { get; set; }
    }
}