// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    public partial class StorageWorkerShifts
    {
        public int WorkerId { get; set; }
        public int StorageId { get; set; }
        public DateTime StartedShiftAt { get; set; }
        public DateTime? FinishedShiftAt { get; set; }

        public virtual Storages Storage { get; set; }
        public virtual Workers Worker { get; set; }
    }
}