// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models
{
    public partial class TableFiles
    {
        public int Id { get; set; }
        public string TableName { get; set; } = null!;
        public int? RecordId { get; set; }
        public int? FId { get; set; }

        public virtual Files FIdNavigation { get; set; }
    }
}