// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WpfApp1.Models
{
    public partial class Users
    {

        public Users()
        {
            Cards = new HashSet<Cards>();
            DeferredProducts = new HashSet<DeferredProducts>();
            Orders = new HashSet<Orders>();
        }

        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Patronymic { get; set; }
        public string PhoneNumber { get; set; }

        private DateTime? _birthday;
        public DateTime Birthday { get
            {
                return _birthday ?? DateTime.Now;
            }
            set
            {
                _birthday = value;
            }

        }

        public string Email { get; set; }
        public int? OrderCode { get; set; }
        public bool IsMale { get;
            set; 
        }
        public int? CountryId { get; set; }

        [NotMapped]
        public string Gender
        {
            get
            {
                return IsMale ? "мужчина" : "женщина";
            }
            set
            {
                IsMale = value == "мужчина";
            }
        }

        [NotMapped]
        public bool IsFemale
        {
            get
            {
                return !IsMale;
            }
        }

        public virtual Countries Country { get; set; }
        public virtual ICollection<Cards> Cards { get; set; }
        public virtual ICollection<DeferredProducts> DeferredProducts { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}